[package]
name = "sudachi-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
sudachi = { path = "../sudachi", default-features = false }
wit-bindgen = "0.53"
zstd = { version = "0.13", default-features = false, features = ["no_asm"] }

[package.metadata.component]
package = "sudachi:tokenizer"
