// Generated by `wit-bindgen` 0.53.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod sudachi {
    pub mod tokenizer {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod api {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_load_dictionary_cabi<T_: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result1 = {
          let len0 = arg1;
          T_::load_dictionary(<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0)))
        };
        let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
        match result1 {
          Ok(e) => { {
            *ptr2.add(0).cast::<u8>() = (0i32) as u8;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(e);
          } },
          Err(e) => { {
            *ptr2.add(0).cast::<u8>() = (1i32) as u8;
            let vec3 = (e.into_bytes()).into_boxed_slice();
            let ptr3 = vec3.as_ptr().cast::<u8>();
            let len3 = vec3.len();
            ::core::mem::forget(vec3);
            *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
            *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr3.cast_mut();
          } },
        };ptr2
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_load_dictionary<T_: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = i32::from(*arg0.add(0).cast::<u8>());
        match l0 {
          0 => (),
          _ => {
            let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l1, l2, 1);
          },
        }
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_tokenize_cabi<T_: Guest>(arg0: i32,arg1: *mut u8,arg2: usize,arg3: i32,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result1 = {
        let len0 = arg2;
        let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
        T_::tokenize(arg0 as u32, _rt::string_lift(bytes0), arg3 as u8)
      };
      let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result1 {
        Ok(e) => { {
          *ptr2.add(0).cast::<u8>() = (0i32) as u8;
          let vec7 = e;
          let len7 = vec7.len();
          let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (6*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
          let (result7, _cleanup7) = wit_bindgen::rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
          for (i, e) in vec7.into_iter().enumerate() {
            let base = result7.add(i * (6*::core::mem::size_of::<*const u8>()));
            {
              let (t3_0, t3_1, t3_2, ) = e;
              let vec4 = (t3_0.into_bytes()).into_boxed_slice();
              let ptr4 = vec4.as_ptr().cast::<u8>();
              let len4 = vec4.len();
              ::core::mem::forget(vec4);
              *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
              *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
              let vec5 = (t3_1.into_bytes()).into_boxed_slice();
              let ptr5 = vec5.as_ptr().cast::<u8>();
              let len5 = vec5.len();
              ::core::mem::forget(vec5);
              *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
              *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
              let vec6 = (t3_2.into_bytes()).into_boxed_slice();
              let ptr6 = vec6.as_ptr().cast::<u8>();
              let len6 = vec6.len();
              ::core::mem::forget(vec6);
              *base.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
              *base.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
            }
          }
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result7;
        } },
        Err(e) => { {
          *ptr2.add(0).cast::<u8>() = (1i32) as u8;
          let vec8 = (e.into_bytes()).into_boxed_slice();
          let ptr8 = vec8.as_ptr().cast::<u8>();
          let len8 = vec8.len();
          ::core::mem::forget(vec8);
          *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
          *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
        } },
      };ptr2
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_tokenize<T_: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => {
          let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base9 = l1;
          let len9 = l2;
          for i in 0..len9 {
            let base = base9.add(i * (6*::core::mem::size_of::<*const u8>()));
            {
              let l3 = *base.add(0).cast::<*mut u8>();
              let l4 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l3, l4, 1);
              let l5 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l6 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l5, l6, 1);
              let l7 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l7, l8, 1);
            }
          }
          _rt::cabi_dealloc(base9, len9 * (6*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        },
        _ => {
          let l10 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l11 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l10, l11, 1);
        },
      }
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_free_dictionary_cabi<T_: Guest>(arg0: i32,) { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();{
      T_::free_dictionary(arg0 as u32)
    };
  } }
  pub trait Guest {
    /// Load dictionary from .xdic bytes and return a handle id
    #[allow(async_fn_in_trait)]
    fn load_dictionary(xdic_bytes: _rt::Vec::<u8>,) -> Result<u32,_rt::String>;
    /// Tokenize text, returns list of (surface, reading, part-of-speech)
    #[allow(async_fn_in_trait)]
    fn tokenize(handle: u32,text: _rt::String,mode: u8,) -> Result<_rt::Vec::<(_rt::String,_rt::String,_rt::String,)>,_rt::String>;
    /// Free a dictionary handle
    #[allow(async_fn_in_trait)]
    fn free_dictionary(handle: u32,) -> ();
  }
  #[doc(hidden)]

  macro_rules! __export_sudachi_tokenizer_api_cabi{
    ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

      #[unsafe(export_name = "sudachi:tokenizer/api#load-dictionary")]
      unsafe extern "C" fn export_load_dictionary(arg0: *mut u8,arg1: usize,) -> *mut u8 {
        unsafe { $($path_to_types)*::_export_load_dictionary_cabi::<$ty>(arg0, arg1) }
      }
      #[unsafe(export_name = "cabi_post_sudachi:tokenizer/api#load-dictionary")]
      unsafe extern "C" fn _post_return_load_dictionary(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_load_dictionary::<$ty>(arg0) }
      }
      #[unsafe(export_name = "sudachi:tokenizer/api#tokenize")]
      unsafe extern "C" fn export_tokenize(arg0: i32,arg1: *mut u8,arg2: usize,arg3: i32,) -> *mut u8 {
        unsafe { $($path_to_types)*::_export_tokenize_cabi::<$ty>(arg0, arg1, arg2, arg3) }
      }
      #[unsafe(export_name = "cabi_post_sudachi:tokenizer/api#tokenize")]
      unsafe extern "C" fn _post_return_tokenize(arg0: *mut u8,) {
        unsafe { $($path_to_types)*::__post_return_tokenize::<$ty>(arg0) }
      }
      #[unsafe(export_name = "sudachi:tokenizer/api#free-dictionary")]
      unsafe extern "C" fn export_free_dictionary(arg0: i32,) {
        unsafe { $($path_to_types)*::_export_free_dictionary_cabi::<$ty>(arg0) }
      }
    };);
  }
  #[doc(hidden)]
  pub(crate) use __export_sudachi_tokenizer_api_cabi;

  #[cfg_attr(target_pointer_width="64", repr(align(8)))]
  #[cfg_attr(target_pointer_width="32", repr(align(4)))]
  struct _RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
  static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::vec::Vec;

  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub use alloc_crate::string::String;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub use alloc_crate::alloc;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_sudachi_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::sudachi::tokenizer::api::__export_sudachi_tokenizer_api_cabi!($ty with_types_in $($path_to_types_root)*::exports::sudachi::tokenizer::api);
  )
}
#[doc(inline)]
pub(crate) use __export_sudachi_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.53.1:sudachi:tokenizer:sudachi:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 323] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc5\x01\x01A\x02\x01\
A\x02\x01B\x0b\x01p}\x01j\x01y\x01s\x01@\x01\x0axdic-bytes\0\0\x01\x04\0\x0fload\
-dictionary\x01\x02\x01o\x03sss\x01p\x03\x01j\x01\x04\x01s\x01@\x03\x06handley\x04\
texts\x04mode}\0\x05\x04\0\x08tokenize\x01\x06\x01@\x01\x06handley\x01\0\x04\0\x0f\
free-dictionary\x01\x07\x04\0\x15sudachi:tokenizer/api\x05\0\x04\0\x19sudachi:to\
kenizer/sudachi\x04\0\x0b\x0d\x01\0\x07sudachi\x03\0\0\0G\x09producers\x01\x0cpr\
ocessed-by\x02\x0dwit-component\x070.245.1\x10wit-bindgen-rust\x060.53.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

